import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { ShiftWithType, HoursSummary } from '../types';
import { formatDate, formatTime, formatDuration } from './dateUtils';

function generateShiftRow(shift: ShiftWithType): string {
  const date = formatDate(shift.start_datetime, 'EEE d MMM yyyy');
  const startTime = formatTime(shift.start_datetime);
  const endTime = formatTime(shift.end_datetime);
  const duration = formatDuration(shift.duration_minutes);
  const bankBadge = shift.is_bank_shift ? ' <span style="background:#005EB8;color:#fff;padding:2px 6px;border-radius:4px;font-size:11px;">BANK</span>' : '';

  return `
    <tr>
      <td style="padding:8px 12px;border-bottom:1px solid #E8EDEE;">
        <span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:${shift.shift_type.colour_hex};margin-right:6px;"></span>
        ${shift.shift_type.name}${bankBadge}
      </td>
      <td style="padding:8px 12px;border-bottom:1px solid #E8EDEE;">${date}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #E8EDEE;">${startTime} – ${endTime}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #E8EDEE;">${duration}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #E8EDEE;">${shift.location ?? '—'}</td>
    </tr>`;
}

function generateBreakdownRows(summary: HoursSummary): string {
  return summary.breakdown
    .map(b => `
      <tr>
        <td style="padding:6px 12px;">
          <span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:${b.colour_hex};margin-right:6px;"></span>
          ${b.type_name}
        </td>
        <td style="padding:6px 12px;">${formatDuration(b.minutes)}</td>
      </tr>`)
    .join('');
}

export async function exportHoursAsPDF(
  summary: HoursSummary,
  periodLabel: string,
  userName: string | null
): Promise<void> {
  const totalHours = formatDuration(summary.total_minutes);
  const contractedStr = summary.contracted_minutes
    ? formatDuration(summary.contracted_minutes)
    : 'Not set';

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #231F20; margin: 0; padding: 24px; }
    .header { background: #005EB8; color: white; padding: 24px; margin: -24px -24px 24px; }
    .header h1 { margin: 0 0 4px; font-size: 22px; }
    .header p { margin: 0; opacity: 0.8; font-size: 14px; }
    .summary-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; margin-bottom: 24px; }
    .summary-card { background: #F0F4F5; border-radius: 8px; padding: 16px; }
    .summary-card .label { font-size: 12px; color: #768692; margin-bottom: 4px; }
    .summary-card .value { font-size: 24px; font-weight: 700; color: #005EB8; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th { background: #F0F4F5; padding: 10px 12px; text-align: left; font-size: 12px; color: #768692; }
    h2 { font-size: 16px; color: #231F20; margin: 24px 0 12px; }
    .footer { margin-top: 32px; font-size: 11px; color: #768692; border-top: 1px solid #E8EDEE; padding-top: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>MyShifts — Hours Report</h1>
    <p>${userName ? `${userName} · ` : ''}${periodLabel}</p>
  </div>

  <div class="summary-grid">
    <div class="summary-card">
      <div class="label">TOTAL HOURS</div>
      <div class="value">${totalHours}</div>
    </div>
    <div class="summary-card">
      <div class="label">CONTRACTED</div>
      <div class="value" style="font-size:20px;color:#425563;">${contractedStr}</div>
    </div>
    <div class="summary-card">
      <div class="label">BANK SHIFTS</div>
      <div class="value" style="font-size:20px;color:#425563;">${formatDuration(summary.bank_minutes)}</div>
    </div>
  </div>

  <h2>Shift Breakdown</h2>
  <table>
    <tr>
      <th>Type</th>
      <th>Hours</th>
    </tr>
    ${generateBreakdownRows(summary)}
  </table>

  <h2>All Shifts (${summary.shifts.length})</h2>
  <table>
    <tr>
      <th>Type</th>
      <th>Date</th>
      <th>Time</th>
      <th>Duration</th>
      <th>Location</th>
    </tr>
    ${summary.shifts.map(generateShiftRow).join('')}
  </table>

  <div class="footer">
    Generated by MyShifts · ${new Date().toLocaleDateString('en-GB')}
  </div>
</body>
</html>`;

  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: `Hours Report — ${periodLabel}`,
    UTI: 'com.adobe.pdf',
  });
}

export async function exportShiftsAsCSV(
  shifts: ShiftWithType[],
  periodLabel: string
): Promise<void> {
  const headers = 'Type,Date,Start,End,Duration (min),Location,Bank Shift,Notes\n';
  const rows = shifts
    .map(s => {
      const date = formatDate(s.start_datetime, 'yyyy-MM-dd');
      const start = formatTime(s.start_datetime, true);
      const end = formatTime(s.end_datetime, true);
      return [
        `"${s.shift_type.name}"`,
        date,
        start,
        end,
        s.duration_minutes,
        `"${s.location ?? ''}"`,
        s.is_bank_shift ? 'Yes' : 'No',
        `"${s.notes ?? ''}"`,
      ].join(',');
    })
    .join('\n');

  const csv = headers + rows;

  // Write to temp file and share
  const { uri } = await Print.printToFileAsync({ html: `<pre>${csv}</pre>` });
  await Sharing.shareAsync(uri, {
    mimeType: 'text/csv',
    dialogTitle: `Shifts Export — ${periodLabel}`,
  });
}
